Add file-name-only output

diff --git a/bin/findstr b/bin/findstr
--- a/bin/findstr
+++ b/bin/findstr
@@ -10,13 +10,32 @@
 if [[ -z "${@+x}" ]] ; then
 	cat << EndOfMessage
 Search within the files of a given directory for a given string, or the current directory if no directory is given.
+The -l|--files-with-matches argument, if provided, will be passed to grep to produce a clean list of file names containing the match.
 Usage examples:
 	$0 mystring
 	$0 /var/log mystring
 	$0 "my string with spaces"
+	$0 -l /var/log mystring
 EndOfMessage
 	exit 1
 fi
+
+while :; do
+	case $1 in
+		"-l"|"--files-with-matches")
+			args="${args} --verbose"
+			GREP_ARGS="${GREP_ARGS} --files-with-matches"
+		;;
+		-*|--*)
+			echo "Invalid argument ($1) provided."
+			exit 1
+		;;
+		*)
+			break
+		;;
+	esac
+	shift
+done
 
 #-> CHECK IF THERE'S TWO (IMPLIED: OR MORE) ARGS
 if [[ ! -z "${2+x}" ]] ; then
@@ -24,7 +43,6 @@ if [[ ! -z "${2+x}" ]] ; then
 	if [ -d "${1}" ]; then
 		DIR="${1}"
 		shift
-		echo ${DIR}
 	else
 		echo "Invalid directory specified."
 		exit 1
@@ -35,6 +53,6 @@ fi
 
 STR=${@}
 
-find ${DIR} -type f -print0 | xargs -0 grep "${STR}"
+find ${DIR} -type f -print0 | xargs -0 grep ${GREP_ARGS} "${STR}"
 
 exit $?
